#pragma once

#define DEFAULT_DESTROY 3.0f
#define DEFAULT_SPEED_PROJECTILE 100.0f
#define DEFAULT_RELATIVE 70.0f
#define DEFAULT_ARROW_LEN 40.0f
#define DEFAULT_TIME_TRIGGER 3.0f
#define DEFAULT_ACTION_DELTA 0
#define DEFAULT_DEQUEUE_PERFRAME 3
